import { Router } from 'express';
import * as ctl from '../controllers/package.controller';
import { authMiddleware } from '../middlewares/auth.middleware';
const router = Router();
router.use(authMiddleware);
router.get('/', ctl.getAll);
router.get('/:id', ctl.getOne);
router.post('/', ctl.create);
router.patch('/:id', ctl.update);
router.delete('/:id', ctl.remove);
export default router;
