import { Router } from 'express';
import * as controller from '../controllers/auth.controller';
import { authMiddleware } from '../middlewares/auth.middleware';
const router = Router();
router.post('/register', controller.register);
router.post('/login', controller.login);
router.get('/me', authMiddleware, controller.me);
router.post('/refresh', controller.refresh);
router.post('/logout', authMiddleware, controller.logout);
export default router;